### ISSUE TITLE
clean install wagtail-opengraph-image-generator gives an error

### ISSUE THREAD

**Issue by ayushin** [candylabshq/wagtail-opengraph-image-generator#5]
```
Traceback (most recent call last):
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/urls/base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'wagtailsettings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/wagtail/admin/urls/__init__.py", line 108, in wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/wagtail/admin/auth.py", line 168, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/wagtail/admin/auth.py", line 59, in wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/wagtail/admin/views/pages.py", line 129, in index
    'do_paginate': do_paginate,
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/wagtail/admin/templatetags/wagtailadmin_tags.py", line 54, in main_nav
    'menu_html': admin_menu.render_html(request),
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/wagtail/admin/menu.py", line 81, in render_html
    menu_items = self.menu_items_for_request(request)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/wagtail/admin/menu.py", line 68, in menu_items_for_request
    return [item for item in self.registered_menu_items if item.is_shown(request)]
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/wagtail/admin/menu.py", line 68, in <listcomp>
    return [item for item in self.registered_menu_items if item.is_shown(request)]
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/wagtail/admin/menu.py", line 104, in is_shown
    return bool(self.menu.menu_items_for_request(request))
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/wagtail/admin/menu.py", line 68, in menu_items_for_request
    return [item for item in self.registered_menu_items if item.is_shown(request)]
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/wagtail/admin/menu.py", line 64, in registered_menu_items
    self._registered_menu_items = [fn() for fn in hooks.get_hooks(self.register_hook_name)]
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/wagtail/admin/menu.py", line 64, in <listcomp>
    self._registered_menu_items = [fn() for fn in hooks.get_hooks(self.register_hook_name)]
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/wagtail/contrib/settings/registry.py", line 48, in menu_hook
    return SettingMenuItem(model, **kwargs)
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/wagtail/contrib/settings/registry.py", line 25, in __init__
    model._meta.app_label, model._meta.model_name]),
  File "/Users/alexis/Work/Python/.virtualenvs/x/lib/python3.7/site-packages/django/urls/base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'wagtailsettings' is not a registered namespace
```

**Comment by ayushin** [comment]
"Getting started" and "Settings" sections of the documentation should mention adding 'wagtail.contrib.settings', to INSTALLED_APPS

**Comment by biki** [comment]
You are right about that, thanks for the heads up.
